version: "2"
services:

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./:/src

  mongo:
    image: mongo:6.0.4
    volumes:
      - './data:/data/db'


